<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>RSpec</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>source.ruby</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(it)\s*((".*")|('.*'))?\s+((do)|{)\s*</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.quoted.rspec</string>
        </dict>
        <key>6</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>end</key>
      <string>^\s*((end)|})\s*$</string>
      <key>endCaptures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.rspec.example</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*(describe|context)\s*((".*")|('.*')|([^\s]*))?\s+((do)|{)\s*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.quoted.rspec</string>
        </dict>
        <key>5</key>
        <dict>
          <key>name</key>
          <string>support.constant.rspec</string>
        </dict>
        <key>7</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>end</key>
      <string>^\s*((end)|})\s*$</string>
      <key>endCaptures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.other.rspec</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.rspec.example.group</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.ruby.rspec</string>
  <key>uuid</key>
  <string>2e080cc5-634a-45e1-9b56-f98887570a81</string>
</dict>
</plist>
